edition = '2021'
group_imports = 'StdExternalCrate'
hard_tabs = false
imports_granularity = 'Crate'
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
