[package]
name = "affects-calculator"
version = "1.0.0"
edition = "2024"

[dependencies]
affects-common = { path = "../affects-common" }
const_format = "0.2"
path-parser = { path = "../path-parser" }
serde_json = "1"
