[package]
name = "path-parser"
version = "1.0.0"
edition = "2024"

[dependencies]
nom = "8"
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
thiserror = "2"

[dev-dependencies]
nom-language = "0.1"
